### ISSUE TITLE
Convert stylegan2-ada tensorflow weights to pytorch

### ISSUE THREAD

**Issue by mayankgrwl97** [rosinality/stylegan2-pytorch#163]
Steps required for converting stylegan2-ada models trained using [official tensorflow repository](https://github.com/NVlabs/stylegan2-ada)

`git clone https://github.com/NVlabs/stylegan2-ada.git`
`python convert_weight.py --repo ~/stylegan2-ada checkpoint.pkl`

Note, if the stylegan2-ada model was trained using `auto` config, the network architecture consists of only 2 mapping layers. Hence, we need to change the mapping layers in the pytorch model from 8 to 2 at the following places:

https://github.com/rosinality/stylegan2-pytorch/blob/master/convert_weight.py#L143
https://github.com/rosinality/stylegan2-pytorch/blob/master/convert_weight.py#L240
https://github.com/rosinality/stylegan2-pytorch/blob/master/convert_weight.py#L251

**Comment by nikhilweee** [comment]
The repository has changed since the last comment. Here are the permalinks to the changes suggested.
https://github.com/rosinality/stylegan2-pytorch/blob/ee0c9ba237717c36cae9de13aec6fd5c368f4540/convert_weight.py#L143
https://github.com/rosinality/stylegan2-pytorch/blob/ee0c9ba237717c36cae9de13aec6fd5c368f4540/convert_weight.py#L240
https://github.com/rosinality/stylegan2-pytorch/blob/ee0c9ba237717c36cae9de13aec6fd5c368f4540/convert_weight.py#L251
