### ISSUE TITLE
convert_weight from .pkl to .pt

### ISSUE THREAD

**Issue by Schatzmin** [rosinality/stylegan2-pytorch#321]
![image](https://user-images.githubusercontent.com/93251898/172154448-8b84adb2-74ce-4ce8-bb8d-cea115abe5ca.png)
![image](https://user-images.githubusercontent.com/93251898/172152845-13390eb9-4859-4126-9434-7f9b84b71ea5.png)
I just used your convert_ weight. py to convert **generator_yellow-stylegan2-config-f.pkl** to .pt file, but there is a bug occurs when loading .pt. Can you tell me which key in the .pt corresponds to which key in the .pkl? Especially the **'g_ema'**.

The above figure is your **train.py**, and the following figure is the official's **run_training.py** based on tensorflow.

**Comment by MarkZXZX** [comment]
> ![image](https://user-images.githubusercontent.com/93251898/172154448-8b84adb2-74ce-4ce8-bb8d-cea115abe5ca.png) ![image](https://user-images.githubusercontent.com/93251898/172152845-13390eb9-4859-4126-9434-7f9b84b71ea5.png) I just used your convert_ weight. py to convert **generator_yellow-stylegan2-config-f.pkl** to .pt file, but there is a bug occurs when loading .pt. Can you tell me which key in the .pt corresponds to which key in the .pkl? Especially the **'g_ema'**.
> 
> The above figure is your **train.py**, and the following figure is the official's **run_training.py** based on tensorflow.

Hi, Do you fix this problem?
I have problems in convert weight, especially I also use "generator_yellow-stylegan2-config-f.pkl"!
Can u give me some insight?

**Comment by Schatzmin** [comment]
> > ![image](https://user-images.githubusercontent.com/93251898/172154448-8b84adb2-74ce-4ce8-bb8d-cea115abe5ca.png) ![image](https://user-images.githubusercontent.com/93251898/172152845-13390eb9-4859-4126-9434-7f9b84b71ea5.png) I just used your convert_ weight. py to convert **generator_yellow-stylegan2-config-f.pkl** to .pt file, but there is a bug occurs when loading .pt. Can you tell me which key in the .pt corresponds to which key in the .pkl? Especially the **'g_ema'**.
> > The above figure is your **train.py**, and the following figure is the official's **run_training.py** based on tensorflow.
> 
> Hi, Do you fix this problem? I have problems in convert weight, especially I also use "generator_yellow-stylegan2-config-f.pkl"! Can u give me some insight?

![image](https://user-images.githubusercontent.com/93251898/175770738-fb5b441f-8678-4485-9a84-dc02d3ebb432.png)
Look, there are **"g"** and **"d"** can be used besides **"g_ema"**. You just need to set **--gen** and **--disc** when you need it.

**Comment by Bai426** [comment]
Can you share your converted checkpoint of generator_yellow-stylegan2-config-f.pt? I tried but failed to convert pkl to pt. The error is like this:
_2022-10-07 08:04:10.853264: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
  File "convert_weight.py", line 248, in <module>
    state_dict = fill_statedict(state_dict, g_ema.vars, size, n_mlp)
  File "convert_weight.py", line 155, in fill_statedict
    update(state_dict, convert_torgb(vars, "G_synthesis/4x4/ToRGB", "to_rgb1"))
  File "convert_weight.py", line 61, in convert_torgb
    weight = vars[source_name + "/weight"].value().eval()
KeyError: 'G_synthesis/4x4/ToRGB/weight'_
