### ISSUE TITLE
Why use nn.Distributed.DataParallel vs. nn.DataParallel

### ISSUE THREAD

**Issue by kylepob** [rosinality/stylegan2-pytorch#56]
Hello! I wanted to ask 2 questions.

1) Why did choose to use Distributed DataParallel instead of normal DataParallel?

2) I tried to modify your code with normal DataParallel, but found that it errors out on the autograd.grad() call in the path regularization loss. Particularly, it indicates that there are unused inputs  and asks that the "allow_unsused" flag be set to True. However, when that flag is set to true, autograd.grad() returns "None" as an output, and we therefore cannot perform the necessary calculations. This does not occur when running in the Distributed DataParallel configuration, but I don't quite understand why. 

Thank you again for your great work, and any help would be appreciated!

**Comment by rosinality** [comment]
1. Generally DistributedDataParallel is more efficient, and in some aspects, it is more simpler to work with DistributedDataParallel. (e.g. you don't need to wo the overheads of gathering generator outputs.)

2. You may need to fake loss which uses generator outputs, like `0 * fake_img[0, 0, 0, 0]` in train.py. But I don't know why because it is not problematic for DataParallel. Or maybe it is because of it calculates gradient respect to latents of generator that internally used in generator, and DataParallel not supports it. Then it will be not possible to implement it with DataParallel.

**Comment by kylepob** [comment]
Ah thank you, for (2) I will try a solution somewhat like 0*fake_img[0,0,0,0]
