### ISSUE TITLE
Roadmap on data augmentation

### ISSUE THREAD

**Issue by Selimonder** [rosinality/stylegan2-pytorch#84]
Hey,
looks like you started implementing newer augmentation(I am guessing this one is from Nvidia paper) techniques for GANs. It seems like there are other methods as well (eg: https://github.com/mit-han-lab/data-efficient-gans). I have a few questions regarding this;

1. What is your plan on merging some of the augmentation techniques for your repo? 
2. Have accomplished fitting smaller datasets into original configuration? 

3. Ref to the pic-- have you experimented with smaller stylegan2 configs with aug, any luck on converging?
(REF)![image](https://user-images.githubusercontent.com/36644230/85197590-4c427c00-b2e2-11ea-8386-5f72f0ff267d.png)

**Comment by rosinality** [comment]
Hello,

1. I have almost implemented non leaking augmentations from NVIDIA paper. But currently I'm not completely sure about some details, for example, up/downsampling with wavelet kernel.

2 & 3. Currently I haven't tried actual training because of the above issues. Anyway I'm considering to do it.
